https://github.com/Lifelong-Robot-Learning/LIBERO

In [10]:
!pip install --quiet mediapy

In [11]:
import mediapy

In [4]:
import os
from libero.libero import benchmark
from libero.libero.envs import OffScreenRenderEnv
from libero.libero import get_libero_path

In [5]:
benchmark_dict = benchmark.get_benchmark_dict()
task_suite_name = "libero_10" # can also choose libero_spatial, libero_object, etc.
task_suite = benchmark_dict[task_suite_name]()

[info] using task orders [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
# retrieve a specific task
task_id = 0
task = task_suite.get_task(task_id)
task_name = task.name
task_description = task.language
task_bddl_file = os.path.join(get_libero_path("bddl_files"), task.problem_folder, task.bddl_file)
print(f"[info] retrieving task {task_id} from suite {task_suite_name}, the " + \
      f"language instruction is {task_description}, and the bddl file is {task_bddl_file}")


[Warning]: datasets path /home/khw/VLA/LIBERO/LIBERO/libero/libero/../datasets does not exist!
[info] retrieving task 0 from suite libero_10, the language instruction is put both the alphabet soup and the tomato sauce in the basket, and the bddl file is /home/khw/VLA/LIBERO/LIBERO/libero/libero/./bddl_files/libero_10/LIVING_ROOM_SCENE2_put_both_the_alphabet_soup_and_the_tomato_sauce_in_the_basket.bddl


In [7]:
# step over the environment
env_args = {
    "bddl_file_name": task_bddl_file,
    "camera_heights": 128,
    "camera_widths": 128
}

In [8]:
env = OffScreenRenderEnv(**env_args)
env.seed(0)
env.reset()
init_states = task_suite.get_task_init_states(task_id) # for benchmarking purpose, we fix the a set of initial states
init_state_id = 0
env.set_init_state(init_states[init_state_id])


[Warning]: datasets path /home/khw/VLA/LIBERO/LIBERO/libero/libero/../datasets does not exist!


/home/khw/VLA/LIBERO/LIBERO/libero/libero/benchmark/__init__.py:164: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  init_states = torch.load(init_states_path)


OrderedDict([('robot0_joint_pos',
              array([-0.01988284, -0.18734066,  0.0076694 , -2.4034026 ,  0.00496468,
                      2.2453365 ,  0.7948479 ])),
             ('robot0_joint_pos_cos',
              array([ 0.99980234,  0.982503  ,  0.99997059, -0.73968777,  0.99998768,
                     -0.62453826,  0.70039334])),
             ('robot0_joint_pos_sin',
              array([-0.01988153, -0.18624675,  0.00766933, -0.67295022,  0.00496466,
                      0.78099421,  0.71375708])),
             ('robot0_joint_vel', array([0., 0., 0., 0., 0., 0., 0.])),
             ('robot0_eef_pos',
              array([-0.03749909, -0.00537552,  0.71296794])),
             ('robot0_eef_quat',
              array([ 0.99981815, -0.01216225,  0.0146372 , -0.00122224])),
             ('robot0_gripper_qpos', array([ 0.020833, -0.020833])),
             ('robot0_gripper_qvel', array([0., 0.])),
             ('agentview_image',
              array([[[ 81,  57,  45],
          

In [29]:
import cv2
import numpy as np
import h5py

# retrieve a specific task
task_id = 0
task = task_suite.get_task(task_id)
task_name = task.name
task_description = task.language
task_bddl_file = os.path.join(get_libero_path("bddl_files"), task.problem_folder, task.bddl_file)
print(f"[info] retrieving task {task_id} from suite {task_suite_name}, the " + \
      f"language instruction is {task_description}, and the bddl file is {task_bddl_file}")


env_args = {
    "bddl_file_name": task_bddl_file,
    "camera_heights": 512,
    "camera_widths": 512
}

env = OffScreenRenderEnv(**env_args)
env.reset()
obs = env.set_init_state(init_states[0])
images = [obs["agentview_image"]]
dummy_action = [0.] * 7
for _ in range(5):
    obs, reward, done, info = env.step(dummy_action)
    # 상하 반전
    flipped_image = obs["agentview_image"][::-1]
    images.append(flipped_image)
    
    
# images = np.concatenate(images, axis=1)
# cv2.imwrite(f"benchmark_tasks/{task.problem}-{task.language}.png", images[::-1, :, ::-1])
env.close()

[Warning]: datasets path /home/khw/VLA/LIBERO/LIBERO/libero/libero/../datasets does not exist!
[info] retrieving task 0 from suite libero_10, the language instruction is put both the alphabet soup and the tomato sauce in the basket, and the bddl file is /home/khw/VLA/LIBERO/LIBERO/libero/libero/./bddl_files/libero_10/LIVING_ROOM_SCENE2_put_both_the_alphabet_soup_and_the_tomato_sauce_in_the_basket.bddl


In [30]:
type(images[0])

numpy.ndarray

In [31]:
mediapy.show_video(images, fps=5)